-- MySQL Script generated by MySQL Workbench
-- Tue Apr 19 15:13:40 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `heathcareDB` DEFAULT CHARACTER SET utf8 ;
USE `heathcareDB` ;

-- -----------------------------------------------------
-- Table `mydb`.`Healthcare Organization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heathcareDB`.`Healthcare Organization` (
  `idHealthcare Organization` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `` INT NOT NULL,
  PRIMARY KEY (`idHealthcare Organization`, ``, `Name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heathcareDB`.`Service` (
  `idService` INT NOT NULL,
  `Drugscreening` TINYINT NOT NULL,
  `expredite` TINYINT NOT NULL,
  `servicedate` DATETIME NULL,
  PRIMARY KEY (`idService`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Supplies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heathcareDB`.`Supplies` (
  `idSupplies` INT NOT NULL,
  `Gloves` VARCHAR(45) NULL,
  `Masks` VARCHAR(45) NULL,
  `Syringes` VARCHAR(45) NULL,
  PRIMARY KEY (`idSupplies`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Maintenance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heathcareDB`.`Maintenance` (
  `idMaintenance` INT NOT NULL,
  `Custodian_name` VARCHAR(45) NULL,
  `Schedule` VARCHAR(45) NULL,
  PRIMARY KEY (`idMaintenance`),
  INDEX `Schedule_idx` (`Schedule` ASC),
  CONSTRAINT `Schedule`
    FOREIGN KEY (`Schedule`)
    REFERENCES `mydb`.`Location` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heathcareDB`.`Location` (
  `idLocation` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Address` VARCHAR(45) NULL,
  PRIMARY KEY (`idLocation`),
  INDEX `Name_idx` (`Name` ASC),
  CONSTRAINT `Name`
    FOREIGN KEY (`Name`)
    REFERENCES `mydb`.`Healthcare Organization` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idLocation `
    FOREIGN KEY (`idLocation`)
    REFERENCES `mydb`.`Service` (`idService`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idLocation`
    FOREIGN KEY (`idLocation`)
    REFERENCES `mydb`.`Supplies` (`idSupplies`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idLocation`
    FOREIGN KEY (`idLocation`)
    REFERENCES `mydb`.`Maintenance` (`idMaintenance`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heathcareDB`.`Employees` (
  `idEmployees` INT NULL,
  `name` VARCHAR(45) NOT NULL,
  `social` VARCHAR(11) NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  `salary` TINYINT(6) NOT NULL,
  `hireDate` DATE NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEmployees`, `role`),
  UNIQUE INDEX `social_UNIQUE` (`social` ASC),
  CONSTRAINT `idEmployees`
    FOREIGN KEY (`idEmployees`)
    REFERENCES `mydb`.`Service` (`idService`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `idEmployees`
    FOREIGN KEY (`idEmployees`)
    REFERENCES `mydb`.`Location` (`idLocation`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Revenue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heathcareDB`.`Revenue` (
  `date` DATETIME NOT NULL,
  `netprofit` VARCHAR(45) NULL,
  `loss` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`date`, `netprofit`, `loss`),
  INDEX `netprofit_idx` (`netprofit` ASC),
  CONSTRAINT `netprofit`
    FOREIGN KEY (`netprofit`)
    REFERENCES `mydb`.`Owner` (`name`)
    ON DELETE SET NULL
    ON UPDATE SET NULL,
  CONSTRAINT `netprofit`
    FOREIGN KEY (`netprofit`)
    REFERENCES `mydb`.`Location` (`Name`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Owner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heathcareDB`.`Owner` (
  `idOwner` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idOwner`, `name`),
  INDEX `idOwner` (`idOwner` ASC),
  INDEX `idOwner_idx` (`name` ASC),
  CONSTRAINT `idOwner`
    FOREIGN KEY (`idOwner`)
    REFERENCES `mydb`.`Location` (`idLocation`)
    ON DELETE SET NULL
    ON UPDATE SET NULL,
  CONSTRAINT `idOwner`
    FOREIGN KEY (`name`)
    REFERENCES `mydb`.`Revenue` (`netprofit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heathcareDB`.`Customer` (
  `idCustomer` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `social` VARCHAR(45) NOT NULL,
  `dateofbirth` DATE NOT NULL,
  `address` VARCHAR(80) NOT NULL,
  `phone` VARCHAR(15) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCustomer`, `social`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Appointment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heathcareDB`.`Appointment` (
  `idAppointment` INT NULL,
  `Appointmentdate` DATETIME NULL,
  PRIMARY KEY (`idAppointment`),
  CONSTRAINT `idAppointment`
    FOREIGN KEY (`idAppointment`)
    REFERENCES `mydb`.`Customer` (`idCustomer`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heathcareDB`.`Account` (
  `idAccount` INT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`idAccount`),
  CONSTRAINT `idAccount`
    FOREIGN KEY (`idAccount`)
    REFERENCES `mydb`.`Customer` (`idCustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idAccount`
    FOREIGN KEY (`idAccount`)
    REFERENCES `mydb`.`Appointment` (`idAppointment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Medical Records`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heathcareDB`.`Medical Records` (
  `idMedical Records` INT NULL,
  `Screeningresults` VARCHAR(45) NULL,
  `Visithistory` VARCHAR(45) NULL,
  `Receipts` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMedical Records`, `Receipts`),
  CONSTRAINT `idMedical`
    FOREIGN KEY (`idMedical Records`)
    REFERENCES `mydb`.`Account` (`idAccount`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heathcareDB`.`Payment` (
  `idPayment` INT NOT NULL,
  `Type` VARCHAR(45) NULL,
  `installment` VARCHAR(45) NULL,
  `amount` VARCHAR(45) NULL,
  PRIMARY KEY (`idPayment`),
  CONSTRAINT `idPayment`
    FOREIGN KEY (`idPayment`)
    REFERENCES `mydb`.`Customer` (`idCustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idPayment`
    FOREIGN KEY (`idPayment`)
    REFERENCES `mydb`.`Account` (`idAccount`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idPayment`
    FOREIGN KEY (`idPayment`)
    REFERENCES `mydb`.`Medical Records` (`idMedical Records`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Medical Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heathcareDB`.`Medical Order` (
  `Prescription` VARCHAR(45) NOT NULL COMMENT '\n',
  `Order_num` INT NULL,
  `order_date` DATE NULL,
  PRIMARY KEY (`Order_num`, `Prescription`),
  CONSTRAINT `Order_date`
    FOREIGN KEY (`Order_num`)
    REFERENCES `mydb`.`Customer` (`idCustomer`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Order Supplies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heathcareDB`.`Order Supplies` (
  `sorder_id` INT NULL,
  `description` VARCHAR(45) NULL,
  `sorder_date` DATE NULL,
  UNIQUE INDEX `sorder_id_UNIQUE` (`sorder_id` ASC),
  CONSTRAINT `sorder_id`
    FOREIGN KEY (`sorder_id`)
    REFERENCES `mydb`.`Employees` (`idEmployees`)
    ON DELETE SET NULL
    ON UPDATE SET NULL,
  CONSTRAINT `sorder_id`
    FOREIGN KEY (`sorder_id`)
    REFERENCES `mydb`.`Location` (`idLocation`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Marketing Campaign`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heathcareDB`.`Marketing Campaign` (
  `campaignid` INT NULL,
  `campaignname` VARCHAR(45) NULL,
  PRIMARY KEY (`campaignid`),
  CONSTRAINT `campaignid`
    FOREIGN KEY (`campaignid`)
    REFERENCES `mydb`.`Location` (`idLocation`)
    ON DELETE SET NULL
    ON UPDATE SET NULL,
  CONSTRAINT `campaignid`
    FOREIGN KEY (`campaignid`)
    REFERENCES `mydb`.`Employees` (`idEmployees`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
